/**
 * This file defines the data schemas and types for the allergy tracking application.
 * It includes definitions for symptom severity ratings, symptom types, and the structure
 * of allergy entries. These schemas are used for data validation and type safety
 * throughout the application, leveraging Zod for runtime validation.
 * Zod is preferred because TypeScript doesn't exist at runtime.
 * 
 * 18/06/2026 Added PollenDataSchema, 
 * Uses overall pollen level considering it's level is a prediction based on historical data and 
 * it is highly dependant on weather (rain, wind, temperature)
 * 
 * How weather affect pollen level: 
 * - Warm, sunny, dry: high pollen count
 * - Rain: lower pollen count
 * - Wind: disperses pollen over long distances
 * 
 * 23/06/2026 Update EntrySchema
 * Add fields: 
 * - _v: track schema version
 * - _synced: true if synced with server, default false 
 * 
 * 17/08/2026 Update EntrySchema
 * Remove fields: 
 * - created_at: generated by server
 * - id: generated by server
 * - user_id: should be derived from token
 */

import { z } from "zod";
import { getTodayDate } from "../utils/dates";

export const SeverityRating = {
  NoSymptom: 0,
  Mild: 1,
  Moderate: 2,
  Severe: 3,
} as const;

export const SeveritySchema = z.union([
  z.literal(SeverityRating.NoSymptom),
  z.literal(SeverityRating.Mild),
  z.literal(SeverityRating.Moderate),
  z.literal(SeverityRating.Severe),
]);

export type SeverityRatingType = z.infer<typeof SeveritySchema>;

export const SymptomSchema = z.enum([
  "eyes",
  "nose",
  "throat",
  "energy",
  "headache",
  "other",
]);

export type Symptom = z.infer<typeof SymptomSchema>;

const ENTRY_LOCAL_SCHEMA_VERSION = 1;

export const EntrySchema = z.object({
  // user_id: z.uuid().optional(),
  // use arrow function getTodayDate so that it is called fresh each time
  date: z.iso
    .date()
    .default(() => getTodayDate())
    .refine((val) => val <= getTodayDate(), {
      message: "Entry date cannot be in the future",
    }), //TODO add constraint: cannot record for older than 3 days (in case of incorrect memory)
  severity: SeveritySchema,
  symptoms: z.array(SymptomSchema).default([]),
  notes: z.string().default(""),
  location: z.string().default('Christchurch Central')
});

export const EntryLocalSchema = EntrySchema.extend({
  _synced: z.boolean().default(false),
  _v: z.literal(ENTRY_LOCAL_SCHEMA_VERSION).default(ENTRY_LOCAL_SCHEMA_VERSION),
})

export const EntryResponseSchema = EntrySchema.extend({
  id: z.uuid(),
  user_id: z.uuid(),
  created_at: z.string(),
});

export type Entry = z.infer<typeof EntrySchema>;
// z.input<> - to allow fields with default value to be optional in forms, can be omitted before parsing
export type EntryInput = z.input<typeof EntryLocalSchema>;
export type EntryLocal = z.infer<typeof EntryLocalSchema>;
export type EntryResponse = z.infer<typeof EntryResponseSchema>;

export const MigrateResponseSchema = z.object({
  synced: z.array(EntryResponseSchema),
  failed: z.array(z.string()), // dates as ISO strings, e.g. "2026-08-14"
});

export type MigrateResponse = z.infer<typeof MigrateResponseSchema>;

// ---- Settings
export const SettingsSchema = z.object({
  notify_time: z.string().regex(/^\d{2}:\d{2}$/).default('20:00'), // HH:MM, 8pm
  notify: z.boolean().default(false),
  location: z.string().default('Christchurch Central') 
});

export type Settings = z.infer<typeof SettingsSchema>;
export type SettingsInput = z.input<typeof SettingsSchema>;

// ---- Pollen schema and type
export const PollenRiskLevelSchema = z.enum(['imminent', 'high', 'moderate', 'low'])
export type PollenRiskLevel = z.infer<typeof PollenRiskLevelSchema>

export const PollenForecastSchema = z.object({
  date: z.string(),       // ISO date 'YYYY-MM-DD'
  location: z.string(),
  imminent: z.array(z.string()),
  low: z.array(z.string()),
  moderate: z.array(z.string()),
  high: z.array(z.string()),
})

export type PollenForecast = z.infer<typeof PollenForecastSchema>
