# AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
from typing import Literal

Valid_locations = Literal[
    "Alexandra",
    "Ashburton",
    "Auckland Central",
    "Balclutha",
    "Banks Peninsula",
    "Blenheim",
    "Cambridge",
    "Carterton",
    "Castlepoint",
    "Christchurch Central",
    "Cromwell",
    "Culverden",
    "Dannevirke",
    "Darfield",
    "Dargaville",
    "Dunedin",
    "Eastern Rangitaiki",
    "Eastern Suburbs",
    "Eltham",
    "Featherston",
    "Feilding",
    "Franz Josef",
    "Gisborne",
    "Glenorchy",
    "Golden Bay",
    "Gore",
    "Greymouth",
    "Haast",
    "Hamilton",
    "Hanmer Springs",
    "Hastings",
    "Havelock North",
    "Hilltop",
    "Hokitika",
    "Hunterville",
    "Huntly",
    "Hunua",
    "Hāwera",
    "Inglewood",
    "Invercargill",
    "Judgeford",
    "Kaiapoi",
    "Kaikohe",
    "Kaikōura",
    "Kaikōura Airport",
    "Kaitaia",
    "Kaitaia Airport",
    "Katikati",
    "Kawerau",
    "Kerikeri",
    "Kumeu",
    "Lake Hayes",
    "Leith Saddle",
    "Levin",
    "Lincoln",
    "Lower Hutt",
    "Lumsden",
    "Lyall Bay",
    "Mahia",
    "Manukau",
    "Marshland",
    "Martinborough",
    "Masterton",
    "Matamata",
    "Methven",
    "Middlemarch",
    "Milford Sound",
    "Morrinsville",
    "Mosgiel",
    "Motueka",
    "Mount Cook",
    "Mount Maunganui",
    "Murchison",
    "Napier",
    "Napier Airport",
    "Nelson",
    "New Plymouth",
    "New Plymouth Airport",
    "Ngongotahā",
    "Ngāruawāhia",
    "North Shore",
    "Nugget Point",
    "Oamaru",
    "Oamaru Airport",
    "Ohakea",
    "Ohakune",
    "Ohariu Valley",
    "Omarama",
    "Opotiki",
    "Opunake",
    "Paeroa",
    "Paihia",
    "Palmerston North",
    "Palmerston North Airport",
    "Papamoa",
    "Paraparaumu",
    "Pegasus",
    "Picton",
    "Piopio",
    "Porirua",
    "Port Chalmers",
    "Port Hills",
    "Prebbleton",
    "Pukekohe",
    "Putāruru",
    "Pōkeno",
    "Queenstown",
    "Raglan",
    "Rakaia",
    "Reefton",
    "Richmond",
    "Rolleston",
    "Rotorua",
    "Ruatoria",
    "Russell",
    "St Arnaud",
    "Stewart Island",
    "Stratford",
    "Takaka",
    "Taumarunui",
    "Taupō",
    "Taupō Airport",
    "Tauranga",
    "Te Anau",
    "Te Aroha",
    "Te Awamutu",
    "Te Horo",
    "Te Kuiti",
    "Te Puke",
    "Temuka",
    "Thames",
    "Timaru",
    "Tokoroa",
    "Tuakau",
    "Twizel",
    "Tūrangi",
    "Upper Hutt",
    "Waiheke Island",
    "Waihi",
    "Waikanae",
    "Waikawau Bay",
    "Waimate",
    "Wainuiomata",
    "Waiouru",
    "Waipara",
    "Waipukurau",
    "Wairoa",
    "Waitakere",
    "Waitati",
    "Waitomo",
    "Warkworth",
    "Wellington Central",
    "Westport",
    "Whakatāne",
    "Whangamatā",
    "Whanganui",
    "Whanganui Airport",
    "Whangārei",
    "Whitianga",
    "Wānaka",
    "Ōhope",
    "Ōmokoroa",
    "Ōtaki",
]
